version: "3"

services:
  database:
    image: mongo:3.4
    volumes:
      - .database:/data/db

  api:
    build: ./api
    ports:
      - 7777:7777
    volumes:
      - ./api:/api
    depends_on:
      - database

  forms:
    build: ./forms
    ports:
      - 8080:8080
    volumes:
      - ./forms:/forms
